version: '3.8'
services:
  app:
    image: computerdreams/getting-started2:node
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3010:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
    image: computerdreams/getting-started2:mysql
    volumes:
      - doit:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
volumes:
  doit: