apiVersion: v1
kind: Service
metadata:
  name: mysql-sv
  labels:
     db: database
spec:
  selector:
    db: database
  ports:
    - port: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    db: database
spec:
  replicas: 1
  selector:
    matchLabels:
      db: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db: database
    spec:
      containers:
        - image: computerdreams/k8s:mysql
          name: mysql-db
  



